Updated instructions for TFE 202109-2 & Cloudrail 1.3.282
indeni/cloudrail-tfe-integration pull request #3
Opened 2021-09-25 12:18 UTC by javierruizjimenez

# Changes to Integration between Terraform Enterprise 202109-2 & Cloudrail 1.3.282

* Deleted multiple docker images to use a single one that includes debugging capabilities and new Cloudrail API URL.
* Simplified Cloudrail Sentinel policies to be loaded into TFE using a VCS
* Unification of Variable names
* Updated instructions and reference to full tutorial at blog post

2021-09-25 12:19 UTC, javierruizjimenez commented
@yi2020 Please review and merge. Thanks!

2021-09-27 15:08 UTC, yi2020 requested changes

2021-09-27 15:08 UTC, yi2020 commented on Readme.md
> +* [Cloudrail account](https://web.cloudrail.app/), with the API key, and your cloud account added
Can we support static analysis - that is, with no cloud account?

2021-09-27 15:08 UTC, yi2020 commented on Readme.md
> +Follow the guide below to integrate Cloudrail into your Terraform Enterprise workspaces or see a detailed tutorial in the [Cloudrail Blog](https://indeni.com/blog/). This will require using a custom
We will need to update the link here once the blog post is made public

2021-09-27 15:08 UTC, yi2020 commented on docker/tfe-cloudrail-worker/Readme.md
> +The Dockerfile includes the common instructions to build a [Terraform Alternative Worker](https://www.terraform.io/docs/enterprise/install/installer.html#alternative-terraform-worker-image) and the r
See link will also need to be updated

2021-09-27 15:08 UTC, yi2020 commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +  if [ "$CLOUDRAIL_DEBUG" = true ]
Why run Cloudrail again under DEBUG, instead of just printing the results?

2021-09-27 15:08 UTC, yi2020 commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +  #if [[ $status -eq 0 || $status -eq 1 ]]; then exit 0; else exit $status; fi
What's this? Should it be removed?

2021-09-27 22:10 UTC, javierruizjimenez commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +[ -z "$CLOUDRAIL_API_KEY" ] && exit 0
Will add it in debug mode, because in order to show a message in the plan output a status > 0 needs to be returned and that is considered an error by Terraform. The Docker image needs to support "Don't run Cloudrail" scenario.

2021-09-27 22:15 UTC, javierruizjimenez commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +  if [ "$CLOUDRAIL_DEBUG" = true ]
To see the full command line used to call Cloudrail. 
The Cloudrail line in DEBUG is an echo, doesn't run cloudrail again.

```
if [ "$CLOUDRAIL_DEBUG" = true ]
  then
    echo cloudrail run  -d /terraform$TF_ATLAS_DIR ....
```
 I will test again.

2021-09-27 22:16 UTC, javierruizjimenez commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +  #if [[ $status -eq 0 || $status -eq 1 ]]; then exit 0; else exit $status; fi
Will clean old code

2021-09-27 22:17 UTC, javierruizjimenez commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +  else # CLOUDRAIL_SENTINEL true or not defined: Sentinel will report issues, accepts status 0 (ok) or 1 (error)
Will update the comment.
In order to run Sentinel step, the Plan step needs to return status 0. So Cloudrail status 1 (mandated rules found violations) needs to be converted to 0. A Sentinel rule will later rise the issue.

2021-10-01 19:14 UTC, javierruizjimenez commented on docker/tfe-cloudrail-worker/finalize_custom_worker.sh
> +  if [ "$CLOUDRAIL_DEBUG" = true ]
Full refactor of debug mode

2021-10-01 19:20 UTC, javierruizjimenez commented
@yi2020 Please review and merge. Thanks!

2021-10-01 19:45 UTC, yi2020 requested changes

2021-10-01 19:45 UTC, yi2020 commented on tfe-cloudrail-sentinel-policies/cloudrail-advisory.sentinel
> +# Cloudrail asessment resulted in "passed_with_warnings"? (some mandated/advised rules are violated)
Remove "mandated/" --- passed_with_warnings are only advised rules violating

2021-10-01 19:45 UTC, yi2020 commented
@javierruizjimenez one small comment left

2021-10-01 20:18 UTC, javierruizjimenez commented on tfe-cloudrail-sentinel-policies/cloudrail-advisory.sentinel
> +# Cloudrail asessment resulted in "passed_with_warnings"? (some mandated/advised rules are violated)
When the API returns `failed_due_to_violations` we don't know if the assessment has also rules that `passed_with_warnings`, so in this implementation the idea is that the Sentinel Advisory rule will **fail** as it has been "overridden" by violations. 

![2021-10-01-22-14-17](https://user-images.githubusercontent.com/29049571/135680998-2117fb7a-2a9b-4121-9589-9b34b50c572d.png)

The alternative is to say to TFE that the Sentinel Advisory rule passed, and it will show that there are **no warnings** in green, bu we don't really know if that is true. `failed_due_to_violations` doesn't let us see the _warnings_.
![2021-10-01-17-53-35](https://user-images.githubusercontent.com/29049571/135681180-2dd599a6-ba48-4195-bb65-258a434dda1a.png)

2021-10-01 20:31 UTC, yi2020 approved these changes

2021-10-01 20:32 UTC, merged

2021-10-01 20:32 UTC, yi2020 commented
@javierruizjimenez merged, good work!